apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
    name: http
  selector:
    app: todo-frontend
