apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.config.dbPassword | quote }}
